(() => {
  // Curated local evidence: no requests, tracking, or destination fetching.
  const FRESH_DAYS = 14;
  const DUE_DAYS = 30;
  const states = {
    VERIFIED_BASICS: { label: 'PATVIRTINTI PAGRINDAI', className: 'verified', note: 'Atlikti nurodyti tapatybės ir šaltinio patikrinimai; tai nėra oficialus Pi patvirtinimas.' },
    CAUTION: { label: 'ATSARGIAI', className: 'caution', note: 'Yra svarbios trūkstamos, pasenusios ar neaiškios informacijos.' },
    LIMITED_DATA: { label: 'RIBOTI DUOMENYS', className: 'limited', note: 'Įrodymų nepakanka prasmingam platesniam vertinimui.' },
    HIGH_RISK: { label: 'VENGTI / DIDELĖ RIZIKA', className: 'risk', note: 'Naudojama tik esant konkrečiam dokumentuotam rimtos rizikos įrodymui.' },
  };
  const records = [
    { slug: 'pi-browser', domains: ['minepi.com'], evidenceState: 'VERIFIED_BASICS', lastReviewed: '2026-08-19', nextReview: '2026-09-18', name: 'Pi Browser', purpose: 'Pi ekosistemos programėlių naršyklė.', audience: 'Pioneer, norintis pasiekti Pi programėles.', checked: 'Peržiūrėtas oficialus Pi Browser pristatymo puslapis ir jo paskirtis.', found: 'Oficialiame puslapyje nurodyta, kad per Pi Browser pasiekiamos ekosistemos programėlės.', limitations: 'PioneerHub neatliko prisijungimo, piniginės ar atskirų programėlių funkcijų testo.', safety: 'Atsidaryk programėles per Pi Browser ir prieš veikdamas patikrink domeną bei prašomus duomenis.', next: 'Naudok oficialias programėlių parduotuvių nuorodas iš Pi šaltinių.', sources: [{ type: 'Oficialus Pi šaltinis', label: 'Pi Browser', url: 'https://minepi.com/pi-browser/' }] },
    { slug: 'pi-wallet', domains: ['wallet.pinet.com'], evidenceState: 'VERIFIED_BASICS', lastReviewed: '2026-08-19', nextReview: '2026-09-18', name: 'Pi Wallet', purpose: 'Pi piniginės prieiga per oficialų Pi adresą.', audience: 'Pioneer, valdantis savo Pi piniginę.', checked: 'Peržiūrėtas oficialus Pi Safety puslapis su oficialių Pi produktų URL sąrašu.', found: 'Pi Safety nurodo wallet.pinet.com kaip Pi Wallet adresą.', limitations: 'PioneerHub netestavo piniginės prisijungimo, likučių ar siuntimo funkcijų.', safety: 'Niekam nesiųsk passphrase ir jos nevesk per gautą nuorodą.', next: 'Adresą atsidaryk savarankiškai, o prieš siuntimą atlik 30 sekundžių patikrą.', sources: [{ type: 'Oficialus Pi šaltinis', label: 'Pi Safety Center', url: 'https://minepi.com/safety/' }] },
    { slug: 'fireside-forum', domains: ['fireside.pinet.com'], evidenceState: 'VERIFIED_BASICS', lastReviewed: '2026-08-19', nextReview: '2026-09-18', name: 'Fireside Forum', purpose: 'Pi bendruomenės diskusijų erdvė.', audience: 'Pioneer, ieškantis bendruomenės pokalbių.', checked: 'Peržiūrėtas oficialus Pi Safety URL sąrašas.', found: 'Fireside Forum oficialus adresas pateiktas Pi Safety puslapyje.', limitations: 'PioneerHub netestavo paskyros, moderavimo ar konkrečių įrašų patikimumo.', safety: 'Bendruomenės įrašai nėra oficialūs pranešimai; tikrink šaltinį savarankiškai.', next: 'Svarbią informaciją palygink su minepi.com oficialiais kanalais.', sources: [{ type: 'Oficialus Pi šaltinis', label: 'Pi Safety Center', url: 'https://minepi.com/safety/' }] },
    { slug: 'pi-chats', domains: ['chat.pinet.com'], evidenceState: 'VERIFIED_BASICS', lastReviewed: '2026-08-19', nextReview: '2026-09-18', name: 'Pi Chats', purpose: 'Pi bendruomenės pokalbiai.', audience: 'Pioneer, bendraujantis Pi ekosistemoje.', checked: 'Peržiūrėtas oficialus Pi Safety URL sąrašas.', found: 'Pi Chats oficialus adresas pateiktas Pi Safety puslapyje.', limitations: 'PioneerHub netestavo pokalbių funkcijų ar vartotojų tapatybių.', safety: 'Žinutėse gauti prašymai siųsti Pi ar atskleisti duomenis turi būti vertinami atsargiai.', next: 'Jei prašoma pinigų ar passphrase, sustok ir atidaryk Safety Center.', sources: [{ type: 'Oficialus Pi šaltinis', label: 'Pi Safety Center', url: 'https://minepi.com/safety/' }] },
    { slug: 'kyc', domains: ['kyc.pinet.com'], evidenceState: 'VERIFIED_BASICS', lastReviewed: '2026-08-19', nextReview: '2026-09-18', name: 'KYC', purpose: 'Pi KYC proceso prieiga per oficialų adresą.', audience: 'Pioneer, vykdantis Pi KYC veiksmus.', checked: 'Peržiūrėtas oficialus Pi Safety URL sąrašas.', found: 'KYC oficialus adresas pateiktas Pi Safety puslapyje.', limitations: 'PioneerHub neatliko KYC proceso ir netikrino asmens duomenų pateikimo eigos.', safety: 'Asmens duomenų nepateik per nuorodas iš žinučių ar neoficialias formas.', next: 'KYC atsidaryk tik per oficialią Pi aplinką ir patikrink adresą.', sources: [{ type: 'Oficialus Pi šaltinis', label: 'Pi Safety Center', url: 'https://minepi.com/safety/' }] },
    { slug: 'pi-launchpad', domains: [], evidenceState: 'LIMITED_DATA', lastReviewed: '2026-08-19', nextReview: '2026-09-02', name: 'Pi Launchpad', purpose: 'Testnet Pi programėlė, skirta susipažinti su Launchpad modeliu.', audience: 'Pioneer, norintis mokytis apie Testnet Launchpad.', checked: 'Peržiūrėtas oficialus Pi Day 2026 pranešimas.', found: 'Pi nurodo, kad pirmoji versija paleista Testnet ir yra testavimo bei mokymosi stadijoje.', limitations: 'PioneerHub netestavo programėlės, jos skaičiavimų, projektų ar bet kokios finansinės rizikos.', safety: 'Testnet ir mokomoji paskirtis nereiškia investicinės rekomendacijos ar garantuoto rezultato.', next: 'Prieš bet kokį veiksmą perskaityk oficialų pranešimą ir tikrink, ar informacija dar aktuali.', sources: [{ type: 'Oficialus Pi šaltinis', label: 'Pi Day 2026 pranešimas', url: 'https://minepi.com/blog/pi-day-2026/' }] },
    { slug: 'cidi-games', domains: [], evidenceState: 'LIMITED_DATA', lastReviewed: '2026-08-19', nextReview: '2026-09-02', name: 'CiDi Games', purpose: 'Pi Browser pasiekiama HTML5 žaidimų platforma.', audience: 'Pioneer, ieškantis žaidimų Pi ekosistemoje.', checked: 'Peržiūrėtas oficialus Pi pranešimas apie beta paleidimą.', found: 'Pi pranešime CiDi Games aprašoma kaip Pi Browser pasiekiama beta žaidimų platforma.', limitations: 'PioneerHub netestavo paskyros, žaidimų, mokėjimų, privatumo ar saugumo praktikų.', safety: 'Beta būsena ir oficialus paminėjimas nepakeičia savarankiško duomenų bei prašomų leidimų tikrinimo.', next: 'Pradėk be jautrių duomenų ir sustok, jei prašoma passphrase ar neaiškaus pervedimo.', sources: [{ type: 'Oficialus Pi šaltinis', label: 'CiDi Games beta pranešimas', url: 'https://minepi.com/announcement/cidi-games-beta/' }] },
  ].map(record => ({ ...record, canonicalId: record.slug }));
  const freshnessFor = (lastReviewed, now = new Date()) => {
    const age = Math.floor((Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), now.getUTCDate()) - Date.parse(`${lastReviewed}T00:00:00Z`)) / 86400000);
    if (age <= FRESH_DAYS) return { key: 'fresh', label: 'Šviežia peržiūra' };
    if (age <= DUE_DAYS) return { key: 'due', label: 'Peržiūra netrukus' };
    return { key: 'overdue', label: 'Peržiūra vėluoja' };
  };
  const findByHostname = hostname => records.find(record => record.domains.includes(String(hostname).toLowerCase()));
  window.PioneerEvidence = { version: 'evidence-v1', records, states, FRESH_DAYS, DUE_DAYS, freshnessFor, findByHostname };
})();
