(() => {
  const reviewed = '2026-08-19';
  const source = { label: 'Pi Safety Center', url: 'https://minepi.com/safety/' };
  const guides = [
    ['Pi Network','pi-network','Kas tai yra ir ko jis nežada.','Pi Network yra ekosistema, kurioje svarbu remtis oficialia informacija, o ne pažadais.','Patikrink naujienas oficialiuose Pi kanaluose.','Nespręsk pagal kainos, atlygio ar „garantijos“ žinutes.'],
    ['Balance Dashboard','balanso-busenos','Kaip skaityti balanso būsenas.','Skirtingos balanso eilutės gali reikšti skirtingą prieinamumo ar migracijos būseną.','Skaityk konkrečios eilutės pavadinimą ir oficialų paaiškinimą.','Nelaikyk rodomo skaičiaus pažadu, kad jis jau prieinamas.'],
    ['Migrated Balance','perkeltas-balansas','Kas jau perkelta į Mainnet.','Perkeltas balansas reiškia būseną tinkle; jo reikšmė priklauso nuo tavo paskyros ir oficialios Pi aplinkos.','Patikrink būseną tik oficialioje Pi aplinkoje.','Nesidalink ekrano nuotraukomis ar piniginės duomenimis su nepažįstamaisiais.'],
    ['Transferable Balance','perkeliamas-balansas','Kodėl tai yra įvertis, ne pažadas.','Perkeliamo balanso būsena gali keistis pagal paskyros ir tinklo procesus.','Stebėk oficialų Checklist ir paskyros pranešimus.','Nesumokėk niekam už „greitesnį perkėlimą“.'],
    ['Unverified Balance','nepatvirtintas-balansas','Ką gali reikšti nepatvirtinta dalis.','Neatpažinta ar nepatvirtinta dalis nėra automatinis praradimo ar būsimo gavimo patvirtinimas.','Perskaityk oficialų paaiškinimą savo paskyroje.','Netikėk žinutėmis, kurios siūlo „atrakinti“ balansą už mokestį.'],
    ['Mainnet','mainnet','Ką keičia migracija.','Migracija ir prieiga prie Pi priklauso nuo oficialių procesų bei tavo paskyros būsenos.','Naudok tik oficialius Pi kanalus ir Checklist.','Neįvesk passphrase į nuorodas iš žinučių.'],
    ['Pi Wallet','pi-wallet','Kur saugiai ją atidaryti.','Pi Safety nurodo wallet.pinet.com kaip oficialų Pi Wallet adresą.','Adresą įvesk pats arba atsidaryk per oficialią Pi aplinką.','Nesiųsk ir niekam nerodyk wallet passphrase.'],
    ['KYC','kyc','Kodėl naudoti tik oficialią aplinką.','Pi Safety nurodo kyc.pinet.com kaip oficialų KYC adresą.','KYC pradėk tik per oficialią Pi aplinką.','Nesiųsk dokumentų per DM, el. pašto nuorodas ar neaiškias formas.'],
    ['Mainnet Checklist','mainnet-checklist','Ką pasitikrinti ramiai.','Checklist žingsniai priklauso nuo individualios paskyros būsenos.','Atidaryk jį oficialioje Pi aplinkoje ir vykdyk tik aiškius veiksmus.','Nesinaudok „pagalbininkais“, prašančiais prisijungimo ar wallet duomenų.'],
    ['Lockup','lockup','Ką reiškia ribotas prieinamumas.','Lockup gali riboti prieigą pagal tavo pasirinkimus ir rodomas sąlygas.','Prieš keisdamas nustatymus perskaityk oficialų tekstą.','Nelaikyk lockup greito pelno ar garantuotos grąžos priemone.'],
    ['Referral Team','referral-team','Ką reiškia komandos struktūra.','Referral Team yra paskyros struktūros dalis, kurios būsena gali priklausyti nuo oficialių procesų.','Tikrink informaciją savo paskyroje.','Nemokėk už „komandos aktyvavimą“.'],
    ['Security Circle','security-circle','Kaip veikia socialinio pasitikėjimo dalis.','Security Circle susijęs su žmonėmis, kuriuos pažįsti ir kuriais pasitiki.','Rinkis tik realiai pažįstamus žmones.','Nesidalink slapta informacija vien dėl prašymo prisijungti.'],
    ['KYC Validator','kyc-validator','Atsakomybė ir privatumas.','KYC Validator veikla gali turėti oficialias sąlygas ir atsakomybes.','Prieš pradėdamas perskaityk aktualias oficialias instrukcijas.','Nekopijuok ir neskelbk kitų žmonių duomenų.'],
    ['Node','node','Kam skirtas techninis dalyvavimas.','Node yra techninis dalyvavimo būdas, kuriam reikia suprasti oficialius reikalavimus.','Pradėk nuo oficialios Pi Node dokumentacijos.','Nesisiųsk neoficialių „Node greitintuvų“ ar raktų.'],
    ['Pi Browser ir appsai','pi-browser-apps','Kaip pradėti saugiai.','Pi Browser skirtas Pi ekosistemos programėlėms pasiekti.','Pradėk nuo oficialių Pi šaltinių ir tikrink programėlės domeną.','Nelaikyk kiekvienos programėlės oficialiai sertifikuota vien dėl pavadinimo.'],
  ].map(([title,slug,short,meaning,action,avoid]) => ({title,slug,short,meaning,action,avoid}));
  const esc = v => String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const date = new Intl.DateTimeFormat('lt-LT',{year:'numeric',month:'long',day:'numeric'}).format(new Date(`${reviewed}T12:00:00Z`));
  const renderHome = (root, query, track) => { if (!root) return; const q=query.toLocaleLowerCase('lt'); const shown=guides.filter(g=>`${g.title} ${g.short} ${g.slug} balansas wallet piniginė migration perkėlimas`.toLocaleLowerCase('lt').includes(q)); root.innerHTML=shown.map(g=>`<article><span class="badge resource">${esc(g.title)}</span><h3>${esc(g.short)}</h3><p>${esc(g.meaning)}</p><a class="text-link" href="/mokykis/${g.slug}">Atidaryti pilną gidą →</a></article>`).join('')||'<p>Nerasta temos. Bandyk: KYC, wallet, piniginė, balansas ar perkėlimas.</p>'; root.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>track?.('learn_article_open'))); };
  const page = () => { const root=document.querySelector('#learnGuide'); if(!root)return; const guide=guides.find(g=>`/mokykis/${g.slug}`===location.pathname); if(!guide)return; document.title=`${guide.title} | Mokykis | PioneerHub`; root.innerHTML=`<article class="radar-detail"><a class="radar-back" href="/#learn">← Grįžti į Mokykis</a><p class="eyebrow">MOKYKIS</p><h1>${esc(guide.title)}</h1><section><h2>Trumpas atsakymas</h2><p>${esc(guide.short)}</p></section><section><h2>Ką tai reiškia</h2><p>${esc(guide.meaning)}</p></section><section><h2>Ką daryti</h2><p>${esc(guide.action)}</p></section><section><h2>Ko nedaryti / dažnos klaidos</h2><p>${esc(guide.avoid)}</p></section><section><h2>Jei kyla problema</h2><p>Sustok, nevesk jautrių duomenų ir patikrink per oficialų Pi šaltinį. Dėl nuorodų, passphrase ar siuntimo naudok <a href="/sauga">Safety Center</a>.</p></section><section><h2>Oficialūs šaltiniai</h2><p><a href="${source.url}" target="_blank" rel="noreferrer">${source.label} ↗</a></p></section><section><h2>Paskutinį kartą peržiūrėta</h2><p>${date}</p></section></article>`; };
  window.PioneerLearn={renderHome,guides}; if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',page,{once:true});else page();
})();
