(() => {
  const evidence = window.PioneerEvidence;
  if (!evidence) throw new Error('PioneerEvidence must load before App Radar');
  const { FRESH_DAYS, DUE_DAYS, states: STATUS, freshnessFor } = evidence;
  const records = evidence.records.map(record => ({ ...record, status: record.evidenceState, unverified: record.limitations, finding: record.found }));

  const injectCss = () => { if (!document.getElementById('radar-v2-style')) { const link = document.createElement('link'); link.id = 'radar-v2-style'; link.rel = 'stylesheet'; link.href = '/radar-v2.css?v=testnet-payment-checklist-v1'; document.head.append(link); } };
  const esc = value => String(value).replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[char]);
  const dateFormat = value => new Intl.DateTimeFormat('lt-LT', { year: 'numeric', month: 'long', day: 'numeric' }).format(new Date(`${value}T12:00:00Z`));
  const badge = record => { const fresh = freshnessFor(record.lastReviewed); return `<span class="radar-status ${STATUS[record.status].className}">${STATUS[record.status].label}</span><span class="freshness ${fresh.key}">${fresh.label}</span>`; };
  const card = record => `<article class="radar-card"><div>${badge(record)}</div><h3>${esc(record.name)}</h3><p>${esc(record.purpose)}</p><p><strong>Esminė išvada:</strong> ${esc(record.finding)}</p><p class="radar-meta-line"><span>Peržiūrėta: ${dateFormat(record.lastReviewed)}</span></p><a class="button primary" href="/radar/${record.slug}">Peržiūrėti</a></article>`;
  const renderHome = (root, track) => {
    if (!root) return; injectCss();
    root.innerHTML = `<div class="radar-toolbar"><input id="radarSearch" type="search" placeholder="Ieškoti programėlės" aria-label="Ieškoti App Radar programėlių"><select id="radarStatus" aria-label="Filtruoti pagal būseną"><option value="">Visos būsenos</option>${Object.entries(STATUS).map(([key, value]) => `<option value="${key}">${value.label}</option>`).join('')}</select><select id="radarFreshness" aria-label="Filtruoti pagal peržiūros šviežumą"><option value="">Visas šviežumas</option><option value="fresh">Šviežia peržiūra</option><option value="due">Peržiūra netrukus</option><option value="overdue">Peržiūra vėluoja</option></select></div><div class="radar-grid" aria-live="polite"></div>`;
    const grid = root.querySelector('.radar-grid'); const search = root.querySelector('#radarSearch'); const status = root.querySelector('#radarStatus'); const fresh = root.querySelector('#radarFreshness');
    const update = () => { const query = search.value.trim().toLocaleLowerCase('lt'); const filtered = records.filter(record => (!query || `${record.name} ${record.purpose}`.toLocaleLowerCase('lt').includes(query)) && (!status.value || record.status === status.value) && (!fresh.value || freshnessFor(record.lastReviewed).key === fresh.value)); grid.innerHTML = filtered.length ? filtered.map(card).join('') : '<p>Nerasta atitinkančių įrašų.</p>'; grid.querySelectorAll('a').forEach(link => link.addEventListener('click', () => track?.('app_radar_view'))); };
    [search, status, fresh].forEach(control => control.addEventListener('input', update)); update();
  };
  const methodology = () => `<article class="radar-detail"><a class="radar-back" href="/#radar">← Grįžti į App Radar</a><p class="eyebrow">APP RADAR METODIKA</p><h1>Kaip vertiname Pi programėles</h1><p>App Radar yra nepriklausomas informacinis įrankis. Jis nėra Pi Network sertifikavimas, patvirtinimas ar investicinė rekomendacija.</p><section><h2>Ką tikriname</h2><p>Priklausomai nuo įrašo, tikriname viešus oficialius šaltinius, nurodytą paskirtį, oficialius domenus ir aiškiai užrašome atliktos peržiūros apimtį.</p></section><section><h2>Kaip skiriamos būsenos</h2><ul>${Object.values(STATUS).map(item => `<li><strong>${item.label}:</strong> ${item.note}</li>`).join('')}</ul></section><section><h2>Šviežumas</h2><p>Iki ${FRESH_DAYS} dienų po peržiūros rodoma „Šviežia peržiūra“, iki ${DUE_DAYS} dienų — „Peržiūra netrukus“, vėliau — „Peržiūra vėluoja“. Pasenęs įrašas nėra automatiškai pavojingas, bet jo išvada neturi būti laikoma aktualia be naujos patikros.</p></section><section><h2>Įrodymai ir ribos</h2><p>Kiekviename įraše atskiriame tai, kas rasta šaltiniuose, nuo to, ko PioneerHub nepatikrino. Oficialus šaltinis gali patvirtinti kilmę, bet ne visų funkcijų, privatumo ar saugumo kokybę.</p></section></article>`;
  const detail = record => `<article class="radar-detail"><a class="radar-back" href="/#radar">← Grįžti į App Radar</a><div>${badge(record)}</div><h1>${esc(record.name)}</h1><p>${esc(record.purpose)}</p><p><strong>Kam skirta:</strong> ${esc(record.audience)}</p><section><h2>Ką PioneerHub patikrino</h2><p>${esc(record.checked)}</p></section><section><h2>Ką radome</h2><p>${esc(record.found)}</p></section><section><h2>Ko negalėjome patikrinti</h2><p>${esc(record.unverified)}</p></section><section><h2>Saugos pastaba</h2><p>${esc(record.safety)}</p></section><section><h2>Saugus kitas žingsnis</h2><p>${esc(record.next)}</p></section><section><h2>Šaltiniai</h2><ul>${record.sources.map(source => `<li><span>${esc(source.type)}: </span><a href="${esc(source.url)}" target="_blank" rel="noreferrer">${esc(source.label)} ↗</a></li>`).join('')}</ul></section><section><h2>Peržiūra</h2><p>Paskutinį kartą peržiūrėta: ${dateFormat(record.lastReviewed)}. Kita planuojama peržiūra: ${dateFormat(record.nextReview)}.</p></section></article>`;
  const renderPage = () => { const root = document.querySelector('#radarApp'); if (!root) return; injectCss(); const path = window.location.pathname; if (path === '/radar/metodika') { document.title = 'App Radar metodika | PioneerHub'; root.innerHTML = methodology(); return; } const record = records.find(item => `/radar/${item.slug}` === path); if (!record) return; document.title = `${record.name} | App Radar | PioneerHub`; root.innerHTML = detail(record); };
  window.PioneerRadar = { records, renderHome, renderPage, freshnessFor, FRESH_DAYS, DUE_DAYS };
  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', renderPage, { once: true }); else renderPage();
})();
