(() => {
  const FRESH_DAYS = 14;
  const DUE_DAYS = 30;
  const STATUS = {
    VERIFIED_BASICS: { label: 'PATVIRTINTI PAGRINDAI', className: 'verified', note: 'Atlikti nurodyti tapatybės ir šaltinio patikrinimai; tai nėra oficialus Pi patvirtinimas.' },
    CAUTION: { label: 'ATSARGIAI', className: 'caution', note: 'Yra svarbios trūkstamos, pasenusios ar neaiškios informacijos.' },
    LIMITED_DATA: { label: 'RIBOTI DUOMENYS', className: 'limited', note: 'Įrodymų nepakanka prasmingam platesniam vertinimui.' },
    HIGH_RISK: { label: 'VENGTI / DIDELĖ RIZIKA', className: 'risk', note: 'Naudojama tik esant konkrečiam dokumentuotam rimtos rizikos įrodymui.' },
  };
  const records = [
    { slug: 'pi-browser', name: 'Pi Browser', purpose: 'Pi ekosistemos programėlių naršyklė.', audience: 'Pioneer, norintis pasiekti Pi programėles.', status: 'VERIFIED_BASICS', lastReviewed: '2026-08-19', nextReview: '2026-09-18', finding: 'Oficialus Pi puslapis nurodo Pi Browser kaip vietą Pi programėlėms pasiekti.', checked: 'Peržiūrėtas oficialus Pi Browser pristatymo puslapis ir jo paskirtis.', found: 'Oficialiame puslapyje nurodyta, kad per Pi Browser pasiekiamos ekosistemos programėlės.', unverified: 'PioneerHub neatliko prisijungimo, piniginės ar atskirų programėlių funkcijų testo.', safety: 'Atsidaryk programėles per Pi Browser ir prieš veikdamas patikrink domeną bei prašomus duomenis.', next: 'Naudok oficialias programėlių parduotuvių nuorodas iš Pi šaltinių.', sources: [{ type: 'Oficialus Pi šaltinis', label: 'Pi Browser', url: 'https://minepi.com/pi-browser/' }] },
    { slug: 'pi-wallet', name: 'Pi Wallet', purpose: 'Pi piniginės prieiga per oficialų Pi adresą.', audience: 'Pioneer, valdantis savo Pi piniginę.', status: 'VERIFIED_BASICS', lastReviewed: '2026-08-19', nextReview: '2026-09-18', finding: 'Pi Safety nurodo tikslų wallet.pinet.com adresą ir kad passphrase vedama tik ten.', checked: 'Peržiūrėtas oficialus Pi Safety puslapis su oficialių Pi produktų URL sąrašu.', found: 'Pi Safety nurodo wallet.pinet.com kaip Pi Wallet adresą.', unverified: 'PioneerHub netestavo piniginės prisijungimo, likučių ar siuntimo funkcijų.', safety: 'Niekam nesiųsk passphrase ir jos nevesk per gautą nuorodą.', next: 'Adresą atsidaryk savarankiškai, o prieš siuntimą atlik 30 sekundžių patikrą.', sources: [{ type: 'Oficialus Pi šaltinis', label: 'Pi Safety Center', url: 'https://minepi.com/safety/' }] },
    { slug: 'fireside-forum', name: 'Fireside Forum', purpose: 'Pi bendruomenės diskusijų erdvė.', audience: 'Pioneer, ieškantis bendruomenės pokalbių.', status: 'VERIFIED_BASICS', lastReviewed: '2026-08-19', nextReview: '2026-09-18', finding: 'Pi Safety oficialių URL sąraše nurodo fireside.pinet.com.', checked: 'Peržiūrėtas oficialus Pi Safety URL sąrašas.', found: 'Fireside Forum oficialus adresas pateiktas Pi Safety puslapyje.', unverified: 'PioneerHub netestavo paskyros, moderavimo ar konkrečių įrašų patikimumo.', safety: 'Bendruomenės įrašai nėra oficialūs pranešimai; tikrink šaltinį savarankiškai.', next: 'Svarbią informaciją palygink su minepi.com oficialiais kanalais.', sources: [{ type: 'Oficialus Pi šaltinis', label: 'Pi Safety Center', url: 'https://minepi.com/safety/' }] },
    { slug: 'pi-chats', name: 'Pi Chats', purpose: 'Pi bendruomenės pokalbiai.', audience: 'Pioneer, bendraujantis Pi ekosistemoje.', status: 'VERIFIED_BASICS', lastReviewed: '2026-08-19', nextReview: '2026-09-18', finding: 'Pi Safety oficialių URL sąraše nurodo chat.pinet.com.', checked: 'Peržiūrėtas oficialus Pi Safety URL sąrašas.', found: 'Pi Chats oficialus adresas pateiktas Pi Safety puslapyje.', unverified: 'PioneerHub netestavo pokalbių funkcijų ar vartotojų tapatybių.', safety: 'Žinutėse gauti prašymai siųsti Pi ar atskleisti duomenis turi būti vertinami atsargiai.', next: 'Jei prašoma pinigų ar passphrase, sustok ir atidaryk Safety Center.', sources: [{ type: 'Oficialus Pi šaltinis', label: 'Pi Safety Center', url: 'https://minepi.com/safety/' }] },
    { slug: 'kyc', name: 'KYC', purpose: 'Pi KYC proceso prieiga per oficialų adresą.', audience: 'Pioneer, vykdantis Pi KYC veiksmus.', status: 'VERIFIED_BASICS', lastReviewed: '2026-08-19', nextReview: '2026-09-18', finding: 'Pi Safety oficialių URL sąraše nurodo kyc.pinet.com.', checked: 'Peržiūrėtas oficialus Pi Safety URL sąrašas.', found: 'KYC oficialus adresas pateiktas Pi Safety puslapyje.', unverified: 'PioneerHub neatliko KYC proceso ir netikrino asmens duomenų pateikimo eigos.', safety: 'Asmens duomenų nepateik per nuorodas iš žinučių ar neoficialias formas.', next: 'KYC atsidaryk tik per oficialią Pi aplinką ir patikrink adresą.', sources: [{ type: 'Oficialus Pi šaltinis', label: 'Pi Safety Center', url: 'https://minepi.com/safety/' }] },
    { slug: 'pi-launchpad', name: 'Pi Launchpad', purpose: 'Testnet Pi programėlė, skirta susipažinti su Launchpad modeliu.', audience: 'Pioneer, norintis mokytis apie Testnet Launchpad.', status: 'LIMITED_DATA', lastReviewed: '2026-08-19', nextReview: '2026-09-02', finding: 'Oficialiame Pi Day pranešime aprašytas pradinis Testnet leidimas, kuris gali greitai keistis.', checked: 'Peržiūrėtas oficialus Pi Day 2026 pranešimas.', found: 'Pi nurodo, kad pirmoji versija paleista Testnet ir yra testavimo bei mokymosi stadijoje.', unverified: 'PioneerHub netestavo programėlės, jos skaičiavimų, projektų ar bet kokios finansinės rizikos.', safety: 'Testnet ir mokomoji paskirtis nereiškia investicinės rekomendacijos ar garantuoto rezultato.', next: 'Prieš bet kokį veiksmą perskaityk oficialų pranešimą ir tikrink, ar informacija dar aktuali.', sources: [{ type: 'Oficialus Pi šaltinis', label: 'Pi Day 2026 pranešimas', url: 'https://minepi.com/blog/pi-day-2026/' }] },
    { slug: 'cidi-games', name: 'CiDi Games', purpose: 'Pi Browser pasiekiama HTML5 žaidimų platforma.', audience: 'Pioneer, ieškantis žaidimų Pi ekosistemoje.', status: 'LIMITED_DATA', lastReviewed: '2026-08-19', nextReview: '2026-09-02', finding: 'Oficialus Pi pranešimas aprašo CiDi Games beta paleidimą; PioneerHub neatliko nepriklausomo produkto testo.', checked: 'Peržiūrėtas oficialus Pi pranešimas apie beta paleidimą.', found: 'Pi pranešime CiDi Games aprašoma kaip Pi Browser pasiekiama beta žaidimų platforma.', unverified: 'PioneerHub netestavo paskyros, žaidimų, mokėjimų, privatumo ar saugumo praktikų.', safety: 'Beta būsena ir oficialus paminėjimas nepakeičia savarankiško duomenų bei prašomų leidimų tikrinimo.', next: 'Pradėk be jautrių duomenų ir sustok, jei prašoma passphrase ar neaiškaus pervedimo.', sources: [{ type: 'Oficialus Pi šaltinis', label: 'CiDi Games beta pranešimas', url: 'https://minepi.com/announcement/cidi-games-beta/' }] },
  ];

  const css = `.radar-toolbar{display:grid;grid-template-columns:1fr 1fr;gap:.75rem;margin:1.25rem 0}.radar-toolbar input{grid-column:1/-1}.radar-toolbar input,.radar-toolbar select{min-width:0;border:1px solid #d5dced;border-radius:.65rem;padding:.8rem;font:inherit;color:#18366f;background:#fff}.radar-grid{display:grid;gap:1rem}.radar-card,.radar-detail{border:1px solid #d5dced;border-radius:1rem;padding:1rem;background:#fff;min-width:0;box-shadow:0 8px 24px #18366f0d}.radar-card h3,.radar-detail h1{margin:.45rem 0;color:#18366f}.radar-card p,.radar-detail p,.radar-detail li{overflow-wrap:anywhere}.radar-status,.freshness{display:inline-block;border-radius:999px;padding:.3rem .55rem;font-size:.73rem;font-weight:800;letter-spacing:.03em}.radar-status.verified{background:#dff4e5;color:#126d35}.radar-status.caution{background:#fff0c9;color:#875300}.radar-status.limited{background:#e7edf8;color:#3b5688}.radar-status.risk{background:#ffe0df;color:#a22d29}.freshness{background:#eef2f8;color:#40516e}.freshness.due{background:#fff0c9;color:#875300}.freshness.overdue{background:#ffe0df;color:#a22d29}.radar-meta-line{display:flex;flex-wrap:wrap;gap:.5rem;margin:.7rem 0;font-size:.88rem;color:#40516e}.radar-card .button{display:inline-flex;margin-top:.25rem}.radar-detail{max-width:760px;margin:1rem auto}.radar-detail section{border-top:1px solid #e2e7f0;margin-top:1rem;padding-top:1rem}.radar-detail h2{font-size:1.05rem;color:#18366f}.radar-detail a{overflow-wrap:anywhere}.radar-back{display:inline-block;margin-bottom:.75rem}@media(max-width:420px){.radar-toolbar{grid-template-columns:1fr}.radar-toolbar input{grid-column:auto}.radar-card,.radar-detail{padding:.9rem}.radar-meta-line{font-size:.82rem}}`;
  const injectCss = () => { if (!document.getElementById('radar-v2-style')) { const style = document.createElement('style'); style.id = 'radar-v2-style'; style.textContent = css; document.head.append(style); } };
  const esc = value => String(value).replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[char]);
  const dateFormat = value => new Intl.DateTimeFormat('lt-LT', { year: 'numeric', month: 'long', day: 'numeric' }).format(new Date(`${value}T12:00:00Z`));
  const freshnessFor = (lastReviewed, now = new Date()) => {
    const age = Math.floor((Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), now.getUTCDate()) - Date.parse(`${lastReviewed}T00:00:00Z`)) / 86400000);
    if (age <= FRESH_DAYS) return { key: 'fresh', label: 'Šviežia peržiūra' };
    if (age <= DUE_DAYS) return { key: 'due', label: 'Peržiūra netrukus' };
    return { key: 'overdue', label: 'Peržiūra vėluoja' };
  };
  const badge = record => { const fresh = freshnessFor(record.lastReviewed); return `<span class="radar-status ${STATUS[record.status].className}">${STATUS[record.status].label}</span><span class="freshness ${fresh.key}">${fresh.label}</span>`; };
  const card = record => `<article class="radar-card"><div>${badge(record)}</div><h3>${esc(record.name)}</h3><p>${esc(record.purpose)}</p><p><strong>Esminė išvada:</strong> ${esc(record.finding)}</p><p class="radar-meta-line"><span>Peržiūrėta: ${dateFormat(record.lastReviewed)}</span></p><a class="button primary" href="/radar/${record.slug}">Peržiūrėti</a></article>`;
  const renderHome = (root, track) => {
    if (!root) return; injectCss();
    root.innerHTML = `<div class="radar-toolbar"><input id="radarSearch" type="search" placeholder="Ieškoti programėlės" aria-label="Ieškoti App Radar programėlių"><select id="radarStatus" aria-label="Filtruoti pagal būseną"><option value="">Visos būsenos</option>${Object.entries(STATUS).map(([key, value]) => `<option value="${key}">${value.label}</option>`).join('')}</select><select id="radarFreshness" aria-label="Filtruoti pagal peržiūros šviežumą"><option value="">Visas šviežumas</option><option value="fresh">Šviežia peržiūra</option><option value="due">Peržiūra netrukus</option><option value="overdue">Peržiūra vėluoja</option></select></div><div class="radar-grid" aria-live="polite"></div>`;
    const grid = root.querySelector('.radar-grid'); const search = root.querySelector('#radarSearch'); const status = root.querySelector('#radarStatus'); const fresh = root.querySelector('#radarFreshness');
    const update = () => { const query = search.value.trim().toLocaleLowerCase('lt'); const filtered = records.filter(record => (!query || `${record.name} ${record.purpose}`.toLocaleLowerCase('lt').includes(query)) && (!status.value || record.status === status.value) && (!fresh.value || freshnessFor(record.lastReviewed).key === fresh.value)); grid.innerHTML = filtered.length ? filtered.map(card).join('') : '<p>Nerasta atitinkančių įrašų.</p>'; grid.querySelectorAll('a').forEach(link => link.addEventListener('click', () => track?.('app_radar_view'))); };
    [search, status, fresh].forEach(control => control.addEventListener('input', update)); update();
  };
  const methodology = () => `<article class="radar-detail"><a class="radar-back" href="/#radar">← Grįžti į App Radar</a><p class="eyebrow">APP RADAR METODIKA</p><h1>Kaip vertiname Pi programėles</h1><p>App Radar yra nepriklausomas informacinis įrankis. Jis nėra Pi Network sertifikavimas, patvirtinimas ar investicinė rekomendacija.</p><section><h2>Ką tikriname</h2><p>Priklausomai nuo įrašo, tikriname viešus oficialius šaltinius, nurodytą paskirtį, oficialius domenus ir aiškiai užrašome atliktos peržiūros apimtį.</p></section><section><h2>Kaip skiriamos būsenos</h2><ul>${Object.values(STATUS).map(item => `<li><strong>${item.label}:</strong> ${item.note}</li>`).join('')}</ul></section><section><h2>Šviežumas</h2><p>Iki ${FRESH_DAYS} dienų po peržiūros rodoma „Šviežia peržiūra“, iki ${DUE_DAYS} dienų — „Peržiūra netrukus“, vėliau — „Peržiūra vėluoja“. Pasenęs įrašas nėra automatiškai pavojingas, bet jo išvada neturi būti laikoma aktualia be naujos patikros.</p></section><section><h2>Įrodymai ir ribos</h2><p>Kiekviename įraše atskiriame tai, kas rasta šaltiniuose, nuo to, ko PioneerHub nepatikrino. Oficialus šaltinis gali patvirtinti kilmę, bet ne visų funkcijų, privatumo ar saugumo kokybę.</p></section></article>`;
  const detail = record => `<article class="radar-detail"><a class="radar-back" href="/#radar">← Grįžti į App Radar</a><div>${badge(record)}</div><h1>${esc(record.name)}</h1><p>${esc(record.purpose)}</p><p><strong>Kam skirta:</strong> ${esc(record.audience)}</p><section><h2>Ką PioneerHub patikrino</h2><p>${esc(record.checked)}</p></section><section><h2>Ką radome</h2><p>${esc(record.found)}</p></section><section><h2>Ko negalėjome patikrinti</h2><p>${esc(record.unverified)}</p></section><section><h2>Saugos pastaba</h2><p>${esc(record.safety)}</p></section><section><h2>Saugus kitas žingsnis</h2><p>${esc(record.next)}</p></section><section><h2>Šaltiniai</h2><ul>${record.sources.map(source => `<li><span>${esc(source.type)}: </span><a href="${esc(source.url)}" target="_blank" rel="noreferrer">${esc(source.label)} ↗</a></li>`).join('')}</ul></section><section><h2>Peržiūra</h2><p>Paskutinį kartą peržiūrėta: ${dateFormat(record.lastReviewed)}. Kita planuojama peržiūra: ${dateFormat(record.nextReview)}.</p></section></article>`;
  const renderPage = () => { const root = document.querySelector('#radarApp'); if (!root) return; injectCss(); const path = window.location.pathname; if (path === '/radar/metodika') { document.title = 'App Radar metodika | PioneerHub'; root.innerHTML = methodology(); return; } const record = records.find(item => `/radar/${item.slug}` === path); if (!record) return; document.title = `${record.name} | App Radar | PioneerHub`; root.innerHTML = detail(record); };
  window.PioneerRadar = { records, renderHome, renderPage, freshnessFor, FRESH_DAYS, DUE_DAYS };
  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', renderPage, { once: true }); else renderPage();
})();
