const reviewDate = '2026-08-19';
const sourceBox = `<aside class="source-box"><strong>Paskutinį kartą peržiūrėta: ${reviewDate}</strong><p>Trumpa saugumo gairė, ne oficialus Pi sprendimas ar garantija.</p><a href="https://minepi.com/safety" target="_blank" rel="noreferrer">Pi Safety — oficialus šaltinis ↗</a></aside>`;
const layout = content => `<div class="safety-main">${content}${sourceBox}</div>`;
const action = (type, title, body) => `<section class="action-plan ${type}"><p class="action-label">${type === 'stop' ? 'STOP' : type === 'verify' ? 'VERIFY' : 'PROTECT'}</p><h2>${title}</h2><p>${body}</p></section>`;

const guides = {
  '/sauga/passphrase': () => layout(`<div class="guide-head"><p class="safety-kicker">SAFETY CENTER · WALLET</p><h1>Kažkas prašo mano wallet passphrase</h1><p class="safety-lede">Passphrase neįvedama ir nesiunčiama kitam žmogui. Šis gidas nieko neprašo ir nieko nerenka.</p></div><div class="guide">${action('stop','Nesidalink ir neįvesk','Teisėtam support ar bendruomenės žmogui tavo wallet passphrase nereikia. Neatsakyk į prašymą ir nespausk gautos nuorodos.')}<section><h2>Dažni rizikos modeliai</h2><ul><li>„Verifikavimo“, migracijos, atkūrimo ar atlygio pažadai.</li><li>Skuba, baimė prarasti balansą arba tariama support paskyra.</li><li>Netikras wallet, KYC ar reward puslapis, prašantis frazės.</li></ul></section>${action('verify','Jei dar nepasidalinai','Uždaryk gautą puslapį. Oficialų Pi ar wallet adresą atsidaryk pats iš patikimo šaltinio — ne iš žinutės.')}${action('protect','Jei galėjai atskleisti','Nedelsdamas nebekartok frazės kituose puslapiuose. Kreipkis tik per oficialius Pi saugos kanalus ir nesek „atkūrimo agentų“ instrukcijų.')}</div><a class="plain-link" href="/sauga">← Visi saugos scenarijai</a>`),
  '/sauga/itartina-nuoroda': () => layout(`<div class="guide-head"><p class="safety-kicker">SAFETY CENTER · NUORODOS</p><h1>Gavau įtartiną Pi nuorodą</h1><p class="safety-lede">Žinutėje esanti nuoroda nėra įrodymas, kad ji saugi — net jei ji atrodo skubi ar žada atlygį.</p></div><div class="guide">${action('stop','Sustok prieš atidarydamas','Nevesk passphrase, prisijungimo ar kitų wallet duomenų į puslapį, atidarytą iš DM, SMS ar komentaro.')}<section><h2>Patikrink šiuos signalus</h2><ul><li>Ar domenas ir galutinis adresas aiškūs, o ne trumpinta ar klaidinančia nuoroda?</li><li>Ar prašoma „KYC“, migracijos, reward ar skubaus patvirtinimo?</li><li>Ar puslapis prašo frazės, kredencialų arba pinigų?</li><li>Ar siuntėjas apsimeta support, tačiau spaudžia veikti dabar?</li></ul></section>${action('verify','Tikrink savarankiškai','Oficialų Pi šaltinį atidaryk pats naršyklėje. Neik per gautą nuorodą ir nepasitikėk vien logotipu ar ekrano kopija.')}${action('protect','Pranešk be jautrių duomenų','Išsaugok tik ne jautrią informaciją apie įtartiną paskyrą ar nuorodą ir pranešk oficialiais kanalais. Nesiųsk passphrase, seed frazės ar dokumentų.')}</div><a class="plain-link" href="/sauga">← Visi saugos scenarijai</a>`),
  '/sauga/pries-siunciant-pi': () => layout(`<div class="guide-head"><p class="safety-kicker">SAFETY CENTER · 30 SEKUNDŽIŲ</p><h1>Prieš siunčiant Pi: 30 sekundžių patikra</h1><p class="safety-lede">Tai tik gairė. PioneerHub nepradeda ir nesimuliuoja jokio mokėjimo.</p></div><form id="sendCheck" class="check-form"><label><input type="checkbox" name="concern"><span>Nesu tikras dėl gavėjo arba pavedimo paskirties.</span></label><label><input type="checkbox" name="concern"><span>Jaučiu spaudimą, skubą ar baimę prarasti progą.</span></label><label><input type="checkbox" name="concern"><span>Pažadas apie garantuotą grąžą ar atlygį nėra nepriklausomai patikrintas.</span></label><label><input type="checkbox" name="concern"><span>Prašymas kilo iš nežinomo kontakto arba galimo apsimetėlio.</span></label><label><input type="checkbox" name="concern"><span>Negaliu savarankiškai patikrinti pasiūlymo ar gavėjo.</span></label><button class="action-button" type="submit">Įvertinti patikrą</button></form><div id="sendOutcome" class="outcome" aria-live="polite" hidden></div><p class="privacy-note">Pažymėjimai lieka tik šiame naršyklės puslapyje ir nėra siunčiami PioneerHub.</p><a class="plain-link" href="/sauga">← Visi saugos scenarijai</a>`),
};

function home() { return layout(`<p class="safety-kicker">PIONEERHUB SAFETY CENTER · ANONIMIŠKAI</p><h1>Ramus veiksmas prieš riziką.</h1><p class="safety-lede">Pasirink situaciją. Nereikia Pi prisijungimo, niekas neišsaugoma ir nereikia įvesti wallet duomenų.</p><div class="scenario-grid"><a class="scenario" href="/sauga/passphrase"><strong>Kažkas prašo mano passphrase</strong><span>Ką sustabdyti, patikrinti ir apsaugoti dabar.</span><span class="arrow">Atidaryti gidą →</span></a><a class="scenario" href="/sauga/itartina-nuoroda"><strong>Gavau įtartiną Pi nuorodą</strong><span>Atpažink skubą, netikrą domeną ir prašymus atskleisti duomenis.</span><span class="arrow">Atidaryti gidą →</span></a><a class="scenario" href="/sauga/pries-siunciant-pi"><strong>Prieš siunčiant Pi — 30 sekundžių patikra</strong><span>Trumpa gairė prieš negrįžtamą veiksmą.</span><span class="arrow">Pradėti patikrą →</span></a></div><p class="privacy-note">Jei kyla abejonių, nieko nesiųsk ir atidaryk oficialų šaltinį pats.</p>`); }

const app = document.querySelector('#safetyApp');
app.innerHTML = (guides[location.pathname] || home)();
const form = document.querySelector('#sendCheck');
form?.addEventListener('submit', event => {
  event.preventDefault();
  const count = new FormData(form).getAll('concern').length;
  const outcome = document.querySelector('#sendOutcome');
  const state = count === 0 ? 'low' : count < 3 ? 'review' : 'stop';
  const copy = state === 'low' ? ['Mažesnė rizika, bet patikrink dar kartą.', 'Prieš bet kokį veiksmą savarankiškai patvirtink gavėją, sumą ir paskirtį.'] : state === 'review' ? ['Peržiūrėk prieš siųsdamas.', 'Sustok, patikrink pasiūlymą nepriklausomu būdu ir nepasikliauk vien gauta žinute.'] : ['STOP — matomi aukštos rizikos signalai.', 'Nesiųsk Pi. Neįvesk passphrase. Patikrink per oficialų šaltinį ir, jei reikia, pranešk apie apsimetimą.'];
  outcome.className = `outcome ${state}`;
  outcome.innerHTML = `<strong>${copy[0]}</strong><p>${copy[1]}</p>`;
  outcome.hidden = false;
  history.replaceState(null, '', `${location.pathname}#${state}`);
  outcome.scrollIntoView({ behavior: 'smooth', block: 'nearest' });
});
